import GithubSlugger from 'github-slugger';

/**
 * The headings in a body, for the contents list in the margin.
 *
 * **It uses the same slugger `rehype-slug` does.** That is the whole
 * correctness question here: the contents list is a column of links to anchors
 * generated by a completely different pass over the same text, and a hand-rolled
 * slugify would agree with it for every simple heading and then quietly disagree
 * on the first one with an ampersand or an accent. `github-slugger` is a direct
 * dependency for that reason rather than borrowed from rehype-slug's tree.
 *
 * The slugger instance is per-call because it is stateful: it remembers what it
 * has emitted so a document with two "Notes" headings gets `notes` and
 * `notes-1`, exactly as the rendered anchors will.
 *
 * Fenced code is stripped first. A `#` at the start of a line inside a shell
 * block is a comment, not a heading, and would otherwise appear in the contents
 * list of a note about shell scripts.
 */

export type Heading = {
  /** 2 or 3. `#` is the page title and never appears in a body. */
  depth: number;
  text: string;
  slug: string;
};

export function extractHeadings(source: string): Heading[] {
  const withoutCode = source.replace(/^```[\s\S]*?^```/gm, '');
  const slugger = new GithubSlugger();
  const headings: Heading[] = [];

  for (const line of withoutCode.split('\n')) {
    const match = /^(#{2,3})\s+(.+?)\s*#*\s*$/.exec(line);
    if (!match) continue;

    // Strip the inline markup a heading is allowed to carry, so the contents
    // list reads as words rather than as source.
    const text = match[2]
      .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
      .replace(/[*_`]/g, '')
      .trim();

    if (text.length === 0) continue;
    headings.push({ depth: match[1].length, text, slug: slugger.slug(text) });
  }

  return headings;
}
